### ISSUE TITLE
[FEATURE] - Add ability to define custom fields in edit

### ISSUE THREAD

**Issue by FacundoSpira** [premieroctet/next-admin#405]
### Summary

I can be really useful to be able to define custom fields in the edit.
For example, let's say that we have a "User" model with a field "hashedPassword". If we want to have a component to be able to change the user password, it would be really useful to do it in a different field "newPassword", so we can for example only send it when toggling a "change password" button. Then, in the beforeDb hook that was added we can check if the "newPassword" is coming as part of the data, and use its value to hash the password and save it in the "hashedPassword" field.

Right now there's no easy way at least to do this, since custom fields get striped out from the data object (so even creating a custom component for hashedPassword with two inputs, one for hashedPassword and one for newPassword doesn't work, since newPassword is removed from the data object.

### Basic Example

We could implement it with a new field `customFields`, so for example:
```tsx
model {
  User: {
    edit: {
      customFields: {
        newPassword: {
          required: true, 
          input: <PasswordInput />,
          // Can also add format (if we don't need to define a custom input), helperText and tooltip.
        },
      },
    },
  },
}
```

### Drawbacks

Can't see any drawback

**Comment by foyarash** [comment]
Release in v5.4.0, thank you @FacundoSpira !

**Comment by vincentwinkel** [comment]
@foyarash I'm looking [at the doc](https://next-admin-docs.vercel.app/docs/code-snippets#custom-input-form) and trying some stuff, but I dont see any way to access to the full item with this solution.
For example my item is:
```ts
{
  type: 'string' | 'number' | 'json';
  key: string;
  value: string;
}
```
On the edit page, I want to display a different input (text, number or textarea) for `value` based on the `type` field.

Solution: `CustomInputProps` should also include `item` with the current item.

**Comment by foyarash** [comment]
Hi @vincentwinkel thanks for the report, gonna have a look at it

**Comment by vincentwinkel** [comment]
I'm not sure to get it right.

Here is my component (just to test):
```ts
import { CustomInputProps } from '@premieroctet/next-admin';

export default function DynamicInput({ item }: CustomInputProps) {
  return <pre>{JSON.stringify({ item }, null, 2)}</pre>;
}
```
and here how it's called:
```ts
    edit: {
      fields: {
        value: { input: <DynamicInput /> },
      },
    },
```
But it displays (`item` is null):
```
{}
```
What do I miss?

**Comment by foyarash** [comment]
Hello @vincentwinkel 

Are you trying this on an edit page ? Create page ?

I updated the docs about the custom input props. The item prop contains the **initial** data of the record, meaning for creation form it will most likely be null. If you want to access the current form data, we now export a `useFormData` hook.

See the [docs](https://next-admin-docs.vercel.app/docs/api/model-configuration#custominputprops)

**Comment by vincentwinkel** [comment]
It's on the edit page (cf the piece of config I shared above). So the item already exists and the data should be here, but I get `{}`.
Also, even after updating to 7.6.1, I get the error:
```
Cannot find module '@premieroctet/next-admin/utils' or its corresponding type declarations
```
I tried to play with the code source but nothing :(

**Comment by foyarash** [comment]
Is your custom input component a client component ? If thats not the case, can you please try to transform it to a client component ?

I'll fix the error, I made a small mistake, thanks

**Comment by vincentwinkel** [comment]
The problem came from the import directive. I updated to 7.6.2 and thanks, now it works like a charm (both `item` and `formData`).

I dont want to bother but I feel I'm making complex something that could be easy (let me know if I should open a new ticket as it's a different issue).

This is what I have now (still playing with the code, so messy):
```ts
'use client';

import { CustomInputProps } from '@premieroctet/next-admin';
import { SettingType } from '@prisma/client';
import { Checkbox, BaseInput } from '@premieroctet/next-admin/components';
import { useFormData } from '@premieroctet/next-admin/utils';

const Input = ({ format, ...props }: CustomInputProps & { format: SettingType }) => {
  switch (format) {
    case SettingType.STRING:
      return <BaseInput type="text" {...props} />;
    case SettingType.NUMBER:
      return <BaseInput type="number" {...props} />;
    case SettingType.BOOLEAN:
      // return <Switch />;
      return <Checkbox {{...props, type: undefined }} />;
    case SettingType.OBJECT:
      return <BaseInput type="text" {...props} />;
    default:
      return null;
  }
};

export default function DynamicInput(props: CustomInputProps) {
  const { formData } = useFormData();
  const format = (formData?.type?.value || SettingType.STRING) as SettingType;

  return (
    <div>
      <pre>{JSON.stringify(formData, null, 2)}</pre>
      <Input format={format} {...props} />
    </div>
  );
}
```
But I cannot import Switch, or jsonField, Checkbox props arent compatible with `CustomInputProps`, etc...

Like I said previously, my goal is just to change an input based on another value, I dont need to rewrite all the inputs.
Maybe something like this could be possible (not sure if it's possible to call it on every item update):
```ts
    edit: {
      fields: {
        // Example
        value: { format: (item) => item.type.value === 'OBJECT' ? 'json' : 'file' },
      },
  },
```

**Comment by foyarash** [comment]
I think you got the right idea. However, we are not exporting all the components of the lib. For instance the `Checkbox` that's available through import is not the one used in the Form. 

This is kinda related to https://github.com/premieroctet/next-admin/issues/582 so i suggest we continue this in here where you could suggest what would be useful to be exposed
